# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=200, unique=True)),
                ('name_db', models.CharField(max_length=200, null=True)),
                ('dbms', models.CharField(choices=[('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('Neo4j', 'Neo4j')], max_length=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField()),
                ('folder', models.FilePathField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('graph', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
